/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'addLabel' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteLabel' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllLabels' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getLabel' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'initializeDefaultLabels' : IDL.Func([], [], []),
  'renameLabel' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'addLabel' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteLabel' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllLabels' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getLabel' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'initializeDefaultLabels' : IDL.Func([], [], []),
    'renameLabel' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };